[project]
name = "raise-utils"
version = "2.5.2"
authors = [{ name = "Rahul Yedida", email = "ryedida@ncsu.edu" }]
description = "RAISE lab package"
readme = "README.md"
requires-python=">=3.9,<3.13"
dependencies = [
    "cvxopt~=1.3.1",
    "pandas~=2.2.2",
    "numpy==1.26.4",
    "colorama~=0.4.6",
    "hyperopt~=0.2.7",
    "scikit-learn~=1.5.1",
    "imblearn~=0.0",
    "bohb-hpo~=0.5.2",
    "tabulate~=0.8.9",
    "keras>=3.0.0,<4.0.0",
    "statsmodels~=0.14.0",
    "tensorflow>=2.16.2",
]

[dependency-groups]
dev = [
    "pytest~=7.3.2",
    "pytest-cov~=4.1.0",
    "coverage~=7.2.7",
    "cython~=0.29.24",
]

[tool.setuptools.packages.find]
include = ["raise_utils", "raise_utils.*"]
namespaces = false

[tool.ruff]
select = ["E", "F", "I001"]

exclude = [
    ".DS_Store",
    ".git",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache"
]

line-length = 120
target-version = "py312"

[tool.ruff.flake8-quotes]
inline-quotes = "single"

[tool.ruff.pycodestyle]
max-doc-length = 120

[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"
