version: 2.1

workflows:
  sample:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout
      - run:
          name: Install dependencies and compiled package
          command: pip install "uv==0.12.14" && uv sync --frozen
      - run:
          name: Run tests
          command: cd tests && uv run --frozen ./test.sh
    resource_class: large
